### PR TITLE
January 2023 roadmap update

### PR DESCRIPTION
**Pull request by bignimbus**
Happy New Year!

Most of this was copied or adapted from https://github.com/apollographql/apollo-ios/issues/2560#issuecomment-1373317272.

### CODE REVIEW

**Review by calvincestari — APPROVED** [review]
I'm happy adding this, good transparency. @AnthonyMDev - anything changes you had in mind since first writing this list?

**Review by AnthonyMDev — COMMENTED** [review]
We should also add something stating we will be working in parallel on `@defer` support!

**Comment by calvincestari** [comment]
While we're editing this file should we remove the "Future" section? It's so far off I don't think it's even worth talking about at the moment and there's many other things that should be in that list too if we want to keep it around.

**Review by calvincestari — APPROVED** [review]
Good to go!

**Pull request merged**
