### PR TITLE
Update subscriptions tutorial to be compatible with recent changes

### PR DESCRIPTION
**Pull request by calvincestari**
Updates to the [subscriptions tutorial](https://www.apollographql.com/docs/ios/subscriptions/) to make the sample code compatible with recent changes to `WebSocketTransport`, `DefaultInterceptorProvider ` and `ApolloClient `.

Answers #1885

### CODE REVIEW

**Review by designatednerd — APPROVED** [review]
LGTM though this is the documentation, not the tutorial 🤓

Probably ought to wait to merge it until this ships.

**Comment by calvincestari** [comment]
> LGTM though this is the documentation, not the tutorial 🤓

Derpy derp!

**Comment by calvincestari** [comment]
> Probably ought to wait to merge it until this ships.

Is there anything to ship for this still? I believe the underlying changes were released in 0.45; the [changelog specified them as breaking changes](https://github.com/apollographql/apollo-ios/releases/tag/0.45.0).

**Comment by AnthonyMDev** [comment]
Yeah, we should merge this now. Right @designatednerd ?

**Review by AnthonyMDev — APPROVED** [review]

**Comment by designatednerd** [comment]
Ahh I thought some of this was tied to the changes that just got merged. Never mind!

**Pull request merged**
