### PR TITLE
Xcode 12 + iOS 14 + Swift 5.3 + associated Updates

### PR DESCRIPTION
**Pull request by designatednerd**
This branch is where updates for Xcode 12, Swift 5.3, iOS/tvOS 14, watchOS 7, and macOS 11 will live until it comes out of beta. Thus far it includes [will try to keep this up to date]: 

- Pointed Circle at Xcode 12 image
- Added a demo playground for queries, mutations, and subscriptions

If you've got a bugfix or a feature specific to Xcode 12 or the associated Swift/OS versions, please open a PR against this branch rather than against `main`. This branch will not be merged to `main` until the final version of Xcode 12 is released.

### CODE REVIEW

**Comment by danl3v** [comment]
Thanks for this. When using Carthage + Xcode 12 Beta 1 to build Apollo, I ran into a few issues. I think there is something wrong in the beta with the `Substring` implementation, and I am hopeful that these issues will be fixed naturally in an upcoming Xcode beta.

1) SQLite would not build - https://github.com/stephencelis/SQLite.swift/compare/master...danl3v:xcode-12
2) Apollo had a few issues - https://github.com/apollographql/apollo-ios/compare/main...danl3v:xcode-12

**Comment by designatednerd** [comment]
Hey @danl3v - Thanks for the heads up. On Apollo, how did you determine those issues? I am not seeing warnings at any of the places you've changed the code.

**Comment by danl3v** [comment]
We are a version or two back. If you pull down `0.27.1`, open Xcode 12, and archive, I was getting these failures. I'll test on newer versions. Good excuse to update :)

**Comment by danl3v** [comment]
I checked on 0.29.1 and am still not able to build with Carthage. Fixes here for 0.29.1: https://github.com/danl3v/apollo-ios/tree/0.29.1-xcode12

**Comment by designatednerd** [comment]
@danl3v Can you please try with Xcode 12 beta 3? Thank you!

**Comment by danl3v** [comment]
Sure can do. Will be next week since I am out the rest of the week. Will report back here

**Comment by GyroJoe** [comment]
Hey @designatednerd - I'm not that familiar with SwiftPM, but it seems to have trouble handling updates to this branch made via force push (and sadly, Xcode's error message here is not very helpful):
```
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/git -C <snipped>/SourcePackages/repositories/apollo-ios-93144027 rev-parse --verify '851856d9d9191e63c7b7d3417531821ad7c4bc26^{commit}' output:
    fatal: Needed a single revision
```
Possible there's a better way to approach this - for now we just manually update `Package.resolved` on branch updates.

**Comment by designatednerd** [comment]
I suppose that makes sense because when rebasing it updates all the commit hashes, and the hash that was pinned by the `Package.resolved` goes 💥. 

I think long term I still want to keep rebasing rather than merging because it'll make the changeset way less insane when I do merge all this, but I appreciate you posting here so people see this and know how to resolve the issue!

**Comment by danl3v** [comment]
To follow up when archiving apollo with Xcode 12 betas, beta 4 fixes the issue for me. Thanks for the support!

**Comment by designatednerd** [comment]
@danl3v Good to hear confirmation! #1300 also reported this.

**Comment by designatednerd** [comment]
Good news: This branch is working fine on Intel hardware if you need to integrate it immediately
Bad news: I'm still fighting with the Apple Silicon hardware

**Comment by designatednerd** [comment]
I'm going to open a new issue on the Apple Silicon problems and merge this - at this point nobody has silicon macs yet and people need to be able to release tomorrow.

**Pull request merged**
