### PR TITLE
Fix issues with imports and foldering

### PR DESCRIPTION
**Pull request by designatednerd**
Addresses #1829.

### CODE REVIEW

**Comment by designatednerd** [comment]
I confirmed checking out an empty project against the `fix/imports` branch this has fixed imports when building with SPM.

**Review by AnthonyMDev — APPROVED** [review]
Thanks for the quick fix!

**Comment by AnthonyMDev** [comment]
Are we going to add the CI job for `swift build` to this PR, or do that separately?

**Comment by designatednerd** [comment]
Separately since this needs to be merged for the version we're working on to go out

**Pull request merged**
