### PR TITLE
Make filesystem diagram a bit easier to understand

### PR DESCRIPTION
**Pull request by designatednerd**
You know what we need more of in the docs? EMOJI. Also, clearer filesystem diagrams. This PR provides both!

### CODE REVIEW

**Comment by calvincestari** [comment]
The file emoji isn't legible, anything else we could use?

**Comment by calvincestari** [comment]
How about improving the plain old ascii? More branch characters and the forward slash to signify directories. Comments have to get pushed further out so not to confuse with the directory forward slash.

After:
```
MyProject                      // Source root
├─ MyProject.xcodeproj
│  ├─ MyProject/               // Contains app target source files
│  ├─ MyLibraryTarget/         // Contains lib target source files
│  ├─ MyProjectTests/          // Contains test files
```

Before:
```
MyProject // Source root
  | MyProject.xcodeproj
  | - MyProject // Contains app target source files
  | - MyLibraryTarget // Contains lib target source files
  | - MyProjectTests // Contains test files
```

**Comment by designatednerd** [comment]
Good call on lining up the comments, but I'm not seeing where the file emoji isn't legible. Here's what it looks like on the branch preview for me:
Screen Shot 2021-12-13 at 9 01 32 PM

**Comment by calvincestari** [comment]
Yes, that's how it looks for me too. "Not legible" as in I couldn't understand what the image was. I'm not going to push back on this, I'll take any improvements for the win.

**Review by calvincestari — APPROVED** [review]

**Comment by designatednerd** [comment]
Ah, OK. For what it's worth, I find it easier when there's both the structure and the emojis to quickly parse what's a folder and what's a file.

**Pull request merged**
