### PR TITLE
Update dependent keys after a successful load

### PR DESCRIPTION
**Pull request by designatednerd**
Addresses #1365 - @teodorpenkov, can you confirm this fixes your issue? I'm still futzing around on how to test this.

### CODE REVIEW

**Comment by teodorpenkov** [comment]
yes, this fixes the issue, I will think about the test today.

 Thank you

**Comment by teodorpenkov** [comment]
@designatednerd here is a test that verifies it's working. I wouldn't add as it is, because it's messy, maybe if we enhance the Star Wars API with mutations about characters it will allow us to build better test.

If I have the time in the next week or so I will try to come up with something better because this is a bit hidden and it's very easy to miss.

```
withCache(initialRecords: [:]) { (cache) in
      let networkTransport = MockNetworkTransport(body: [
        "data": [
          "hero": [
            "id": "0",
            "name": "Artoo",
            "__typename": "Droid",
            "friends": [
              ["id": "10", "__typename": "Human", "name": "Luke Skywalker"]
            ]
          ]
        ]
      ])

      let store = ApolloStore(cache: cache)
      let client = ApolloClient(networkTransport: networkTransport, store: store)
      client.store.cacheKeyForObject = { $0["id"] }

      let query = HeroAndFriendsNamesWithIDsQuery()
      let expectation = self.expectation(description: "Has friend named Han Solo")
      let initialFetch = self.expectation(description: "Initial fetch")
      initialFetch.assertForOverFulfill = false

      _ = client.watch(query: query) { result in
        initialFetch.fulfill()
        if case let Result.success(result) = result {
          if result.data.flatMap({ $0.hero?.friends?.contains(where: { $0?.name == "Han Solo" })}) == true {
            expectation.fulfill()
          }
        }
      }
      wait(for: [initialFetch], timeout: 1)

      let encahnceInitialQuery = self.expectation(description: "Update initial query")
      store.withinReadWriteTransaction({ transaction in
        try transaction.update(query: query) { (data: inout HeroAndFriendsNamesWithIDsQuery.Data) in
          data.hero?.friends?.append(try .init(jsonObject: ["id": "11", "__typename": "Human", "name": "Not Han Solo"]))
          encahnceInitialQuery.fulfill()
        }
      })
      wait(for: [encahnceInitialQuery], timeout: 1)

      networkTransport.body = [
        "data": [
          "hero": [
            "id": "2",
            "name": "R2-D2",
            "__typename": "Droid",
            "friends": [
              ["id": "11", "__typename": "Human", "name": "Han Solo"]
            ]
          ]
        ]
      ]

      client.fetch(query: HeroAndFriendsNamesWithIdQuery(episode: .newhope), cachePolicy: .fetchIgnoringCacheData)

      waitForExpectations(timeout: 5, handler: nil)
    }
```

**Comment by designatednerd** [comment]
@teodorpenkov Thanks for your help with the idea - I've taken the test and fleshed it out a bit, would love your feedback, but it passes when resetting the dependent keys is there and fails when it's commented out, so I think it should be an effective safety net.

**Review by teodorpenkov — APPROVED** [review]
LGTM

**Comment by designatednerd** [comment]
@teodorpenkov thanks for the inspo on the test, it already caught a massive bug with query watchers on the networking rewrite branch 🙃

**Pull request merged**
