### PR TITLE
[WIP] Fix legacy docs images

### PR DESCRIPTION
**Pull request by Meschreiber**

### CODE REVIEW

**Comment by calvincestari** [comment]
I'm not sure why CircleCI is attempting to run unit and integration tests here..

**Comment by calvincestari** [comment]
Oh wait. This is on the legacy branch so the CI config here is waaaaay out of date. We can ignore that for now.

**Comment by calvincestari** [comment]
@Meschreiber - are you still figuring out changes for this PR or is there something else wrong with the Docs Preview check?

**Comment by Meschreiber** [comment]
Ah, thanks for the ping! This was more of an exploratory branch to see what was going wrong with images. Turns out the issue was in the platform, not in the content, so we can close this.

**Pull request closed without merging**
