### PR TITLE
Update CLI version to 2.33.1 in codegen script

### PR DESCRIPTION
**Pull request by barcister**

### CODE REVIEW

**Comment by AnthonyMDev** [comment]
Thanks for the PR @barcister!

@glasser The apollo-tooling releases don't have any release notes, so I'm not sure what's changed. Should the iOS client be updating to the most recent version of the CLI? Any expected breakages if we do so?

Also, the newest version is now 2.33.4, so we should probably update to that instead of 2.33.1.

**Comment by glasser** [comment]
@AnthonyMDev The way we publish the apollo-tooling packages means that whenever we bump one package, we also bump all packages that depend on them just to bump the dependency.

Looking at https://github.com/apollographql/apollo-tooling/blob/master/CHANGELOG.md I'm not sure there are any super salient changes to the CLI between 2.32.13 and 2.33.1. In fact `git diff --stat apollo@2.32.13 apollo@2.33.1` shows no changes to TypeScript files. 2.33.2 (not in this PR for some reason) does have a big change in the release notes (deprecating the commands that are now in Rover).  between 2.33.2 and 2.33.4 there's one bugfix, I don't know if the method in question is actually used in the CLI (it's in one of the kinda grab-bag utility packages we have).

**Comment by AnthonyMDev** [comment]
Ah that makes sense. Thanks! As long as the commands that are deprecated aren't the ones we are using this is fine. We are writing the Swift codegen, so I don't want to make updates to our CLI usage to migrate to Rover right now in the mean time if we don't have to.

**Comment by designatednerd** [comment]
If we make this change we also need to update the URL/SHASUM in the `SwiftScripts` package - [here's a prior update so you can see where those changes need to be made](https://github.com/apollographql/apollo-ios/pull/1773)

**Comment by calvincestari** [comment]
Closing this in favour of https://github.com/apollographql/apollo-ios/pull/1929 which bumps to the latest CLI release; `2.33.6`

**Pull request closed without merging**
