### PR TITLE
add request to GraphQLHTTPResponseError for easier debugging

### PR DESCRIPTION
**Pull request by RolandasRazma**
Was trying to trace some problems with auth and it was very useful to see what we actually send to server (headers in particular)

### CODE REVIEW

**Comment by designatednerd** [comment]
Hey @RolandasRazma - I'm inclined to decline this one for similar reasons to the discussion in #1116 - you should be able to get the headers from another delegate and if you need more information, your server should really be putting it into the GraphQL error on its end.

**Comment by RolandasRazma** [comment]
thought you will say so :)

**Comment by designatednerd** [comment]
Do you have any other thoughts on this or should I just close it out?

**Comment by RolandasRazma** [comment]
I think you can close it as its limited use, I personally can't use it from delegate but that's more of architectural limitation than Apollo problem

**Pull request closed without merging**
