### PR TITLE
URLSessionClientLiveTests testCleanup

### PR DESCRIPTION
**Pull request by RolandasRazma**
Test for crash described in https://github.com/apollographql/apollo-ios/issues/1473

### CODE REVIEW

**Comment by designatednerd** [comment]
@RolandasRazma Is this designed to be a failing test? It appears to be failing across the board.

**Comment by RolandasRazma** [comment]
yes. It crashes everything - it shouldn't - Test to illustrate problem

**Comment by designatednerd** [comment]
OK. Wasn't clear from your description if this was to reproduce the problem or act as a solution. Thanks for clarifying!

**Comment by RolandasRazma** [comment]
we could fix crash by returning error if you try calling `sendRequest` after URLSessionClient is invalidated

**Comment by designatednerd** [comment]
This was helpful for #1489, that should now validate that invalidating the session returns an error. Going to close this PR out in favor of that one.

**Pull request closed without merging**
