### PR TITLE
Make GraphQLResponse a generic on the response type instead of on the operation type

### PR DESCRIPTION
**Pull request by gsabran**
It looks like there's little reasons to have `GraphQLResponse` be tied to the operation type, instead of more simply to the response type (`.Data`)

I was interested in this change as I use a query wrapper class around the `GraphQLOperation` generated by the codegen. This wrapper allows me to easily set context for my `NetworkTransport` that receives the operation through Apollo. While it shares the same response type as the wrapped operation, it is of a different type and this was not playing well with the `GraphQLResponse`

This slightly changes the public API of `NetworkTransport` as well, but all the changes are straightforward.

### CODE REVIEW

**Comment by designatednerd** [comment]
> While it shares the same response type as the wrapped operation, it is of a different type and this was not playing well with the `GraphQLResponse`

Can you clarify a bit what you mean by this, perhaps by giving an example? 

This looks like a reasonably straightforward changeset, but it is definitely breaking so I'd like to mull it over a little. In the meantime, do you mind fixing the alignment of parameters in the method declarations that broke because you changed the name of the generic type?

**Comment by gsabran** [comment]
Sure. At a high level the wrapper strategy looks like:

```swift
// networking service
class NetworkingService {
  init() {
    self.apolloClient = ApolloClient(transport: NetworkTransport())
  }

  func fetch(query: GraphQLQuery, requestConfiguration: RequestConfiguration, completion: ...) {
    // wrappedQuery is GraphQLQuery with the same Data type, but of different type than query
    let wrappedQuery = WrappedQuery(query, requestConfiguration)
    apolloClient.fetch(wrappedQuery, completion)
  }
}

class NetworkTransport {
  // called from Apollo
  func send(query: GraphQLQuery, completion: ...) {
    let requestConfiguration = (query as? WrappedQuery)?.requestConfiguration
    let request = buildRequest(query.operationName, query.params, requestConfiguration)
    apiSession.send(request, completion)
  }
}
```

**Comment by designatednerd** [comment]
Ahhh ok so this is enabling a custom network transport, that's the piece I was missing in my mental model.

**Comment by designatednerd** [comment]
Updated code looks good, I do want to think this over a bit since it'd be a breaking change.

**Comment by LooTKinGz** [comment]
File update

**Pull request merged**
