### PR TITLE
Updated swift Language version to Swift 4.2.

### PR DESCRIPTION
**Pull request by hirota-ryo**

### CODE REVIEW

**Comment by Dfmarulanda** [comment]
There is any problem with 4.2 update?

**Comment by jstngoulet** [comment]
Any Update?

**Comment by fwal** [comment]
This seems to be superseded by the Swift 5 support in #482

**Comment by designatednerd** [comment]
Confirmed, this is now superseded by Swift 5 support. Sorry we weren't able to get this merged at the time! I'm going to close this out.

**Pull request closed without merging**
