### PR TITLE
Remove empty lines from source files.

### PR DESCRIPTION
**Pull request by abdullahselek**
This is a simple PR that removes the empty lines from source files.

### CODE REVIEW

**Comment by designatednerd** [comment]
Interesting! How did you wind up doing this? 

I'm a little torn - I like it as a general principle thing but I don't want to police new PRs for formatting stuff like this on a regular basis.

**Comment by abdullahselek** [comment]
Yes it is a general principle. If you agree with me we can merge this PR and I will work on enabling https://github.com/realm/SwiftLint on this project to check the coding style and conventions.

**Comment by designatednerd** [comment]
Swift lint's mostly helpful on OSS when Danger's set up to comment on broken rules on PRs - is that something you're also prepared to help add? I'd love to do it myself but at this point I need to focus on the codegen rewrite or it's never going to get done.

**Comment by designatednerd** [comment]
I'm gonna go ahead and merge this PR, as it is a nice-to-have. Ping me via email (ellen at apollographql dot com) about SwiftLint - I'd like to do it, but I'd like to avoid too much rejiggering of things if it's not necessary.

**Comment by abdullahselek** [comment]
Thanks @designatednerd I will ping you 👍

**Pull request merged**
