### PR TITLE
Remove all instances of bitcode as it's not supported in Xcode 14

### PR DESCRIPTION
**Pull request by stareque-atlassian**
Removing "bitcode" as it's not supported in Xcode 14, as mentioned in Xcode release notes
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

### CODE REVIEW

**Comment by stareque-atlassian** [comment]
@calvincestari the ci plan is failing, but I think it should be a flaky test. im unable to rerun them on circle ci

**Comment by AnthonyMDev** [comment]
Yeah, that's a flaky test we are working on resolving right now. This looks good though! We'll get it merged and a release out soon! I know you asked for it to be a patch version, but I think it's probably more appropriate as a minor version because, functionally, it does drop support for Apple Watch Series 3 I think.

**Review by AnthonyMDev — APPROVED** [review]

**Review by AnthonyMDev — APPROVED** [review]

**Comment by stareque-atlassian** [comment]
@AnthonyMDev thanks! If possible can you do a minor update in version 0.x so the minor release would be `0.52.0`. If not possible then we'll try to get our team to migrate to the latest Apollo 1.x

**Comment by AnthonyMDev** [comment]
Oh yes, we will absolutely do that! But I would say, the 1.0 is a HUGE improvement and I’d strongly encourage your team to start migrating over to that as soon as they can! We’re working on documentation and migration guides now, so I’m the next few weeks that should all be there to assist you!

**Pull request merged**
