### PR TITLE
docs: remove preview status from persisted queries

### PR DESCRIPTION
**Pull request by Meschreiber**
Do not merge until PQs are officially in GA.

### CODE REVIEW

**Review by BobaFetters — APPROVED** [review]
Depending on when this needs merged in we may need to transition this PR over to our new `apollo-ios-dev` repo that we will be fully switching over to for development soon. More info on that [here](https://github.com/apollographql/apollo-ios/issues/3240). The docs team has a PR up to be merged in soon to start publishing the docs from that new repo so will just need to keep an eye on the timing of this.

**Comment by Meschreiber** [comment]
Ah, thanks for the callout @BobaFetters . PQ GA is next week. I'll be sure to make this change in the apollo-ios-dev repo if the docs PR merges first.

**Comment by Meschreiber** [comment]
@BobaFetters , just wanted to double check there's nothing extra to do in regards to `apollo-ios-dev` since [this PR](https://github.com/apollographql/docs/pull/568) hasn't been merged yet. Is that right?

**Comment by BobaFetters** [comment]
@Meschreiber nope this is all good, ill take care of making sure the changes in `apollo-ios` are all merged into `apollo-ios-dev` before we release

**Pull request merged**
