### PR TITLE
Release/1.5

### PR DESCRIPTION
**Pull request by AnthonyMDev**
#### Diff

[1.4.0...release/1.5](https://github.com/apollographql/apollo-ios/compare/1.4.0...release/1.5)

#### Things to do in this PR
- [x] Update the version constants using the `set-version.sh` script.
- [x] Update [`CHANGELOG.md`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md) with all relevant changes since the prior version. _Please include PR numbers and mention contributors for external PR submissions._
- [x] Run the Documentation Generator from the internal `SwiftScripts` folder using the command `swift run DocumentationGenerator` to re-generate the API reference documentation from source for all included libraries. _Make sure you are on HEAD of the parent branch otherwise the documentation generator will not catch all changes, rebase this PR if needed._

#### Things to do as part of releasing
- [ ] Add tag of format `major.minor.patch` to GitHub.
- [ ] Create a release on GitHub with the new tag, using the latest [`CHANGELOG.md`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md) contents.
- [ ] Attach CLI binary to the GitHub release. _Use the `make archive-cli-for-release` command which builds both Intel and ARM architectures, and creates the tar archive for you._
- [ ] Run `pod trunk push Apollo.podspec` to publish to CocoaPods. _You will need write permissions for this, please contact one of the [maintainers](https://github.com/apollographql/apollo-ios/blob/main/README.md#maintainers) if you need access to do this._

### CODE REVIEW

**Review by calvincestari — COMMENTED** [review]
There's a lot of changes here to the API documentation which seem to extend beyond the scope of just the changes we're including in this release. I'm not sure if they're all correct.

**Comment by calvincestari** [comment]
I think the diff at the top of the PR description should be [1.4.0...main](https://github.com/apollographql/apollo-ios/compare/1.4.0...main) instead of [main...release/1.5](https://github.com/apollographql/apollo-ios/compare/main...release/1.5). It makes it easier to see the merged changes that would go out with the release.

**Comment by AnthonyMDev** [comment]
> There's a lot of changes here to the API documentation which seem to extend beyond the scope of just the changes we're including in this release. I'm not sure if they're all correct.

I noticed this too. I looked at it and it looks like it's a lot of references to Foundation and Swift Standard Library stuff that was removed. I'm assuming this was a change to SwiftDoCC itself.

**Review by calvincestari — APPROVED** [review]
Approving so we can merge this. and since documentation updates don't require a new release we can fix anything wrong with the documentation outside of the release cycle.

**Pull request merged**
