### PR TITLE
Support Auto-Persisted Queries

### PR DESCRIPTION
**Pull request by designatednerd**
This is an update of work started in #608. However, we're running into an issue where stripping whitespace out of queries is causing APQ validation to fail, because the SHA256 hash no longer matches. I need to figure out if there's a way around this or if I need to just suck it up and use multiline string literals (cc @lilyball). 

Leaving this in draft until I can figure out, but @codebear98 would love feedback on some of the restructuring I did in the merge.

### CODE REVIEW

**Comment by designatednerd** [comment]
This is now waiting on [some changes to tooling](https://github.com/apollographql/apollo-tooling/pull/1537)

**Comment by designatednerd** [comment]
Okay! Will need to merge this again once #821 gets merged, but this shouuuuuuld be about ready to go

**Comment by fiznool** [comment]
This is really great. ❤️ 

So far I guess we can look at the test files for examples, but are there any plans to add a section in the docs regarding how to set this up?

**Comment by designatednerd** [comment]
Added #951 to my todo list @fiznool

**Pull request merged**
