### PR TITLE
make `-[ApolloStore clearCache]` public

### PR DESCRIPTION
**Pull request by RolandasRazma**
followup to https://github.com/apollographql/apollo-ios/pull/517

make `-[ApolloStore clearCache]` public. 

At the moment there is no way to clear cache unless you have access to `ApolloClient`. Having `clearCache()` on `ApolloClient` is not exactly correct as multiple `ApolloClient` can share same cache.

### CODE REVIEW

**Comment by designatednerd** [comment]
So I'm definitely in agreement with making `clearCache` on the `Store` public for the reasons you've outlined. However, I don't think we should deprecate `clearCache` on the client - many users will only be using a single client with a single cache, and for that use case leaving it on the client makes sense. 

How about adding a note to the documentation that if you're using the same cache across multiple, you should call the method on the store instead?

**Comment by RolandasRazma** [comment]
It's bit confusing if we leave it...

```swift
apolloClient.clearCache()
// do I need to call apolloClient.store.clearCache() as well?
```

**Comment by designatednerd** [comment]
@RolandasRazma I think if you're only using one client and one cache (which is a fairly good chunk of our users), leaving it as a convenience would probably be better. 

Having it exposed separately is helpful for the people who need it, but I think for people who only need the one client and the one cache, it's easier to leave the existing behavior and expose the underlying `clear` as a benefit for the people who need it.

**Comment by RolandasRazma** [comment]
IMO it brings unnecessary confusion, but it's your call. Removed deprecation.

**Comment by designatednerd** [comment]
I'll update some of the docs once this is merged to try to make it clearer when to use which one - thank you!

**Pull request merged**
