### PR TITLE
Enable to add additional headers after creating a client

### PR DESCRIPTION
**Pull request by weapon3042**
Right now, additional headers can only be specified when creating a client. This Pull Request provides a solution to add additional headers for each request after creating a client.

### CODE REVIEW

**Comment by martijnwalraven** [comment]
Thanks for submitting this PR. While I agree we need a way to add additional headers after creating a client, I don't think we should specify headers as part of the fetch/mutate methods, both because it leaks HTTP specific details and because I'd like to avoid having to force every caller to keep track of header information.

Instead, I think we'll probably want this to be limited to a specific`NetworkTransport` implementation, like `HTTPNetworkTransport`. We've had [some discussions about this](https://github.com/apollographql/apollo-ios/issues/37) before, and one idea was to use a delegate protocol that allows you to modify a `URLRequest` before it gets sent to the server, similar to [`RequestAdapter`](https://github.com/Alamofire/Alamofire#requestadapter) in Alamofire.

Maybe something like:

```
public protocol HTTPNetworkTransportDelegate: class {
  func networkTransport<Operation: GraphQLOperation>(_ networkTransport: HTTPNetworkTransport, willSend request: inout URLRequest, forOperation operation: Operation)
}
```

Do you think that would help solve your use case?

**Comment by weapon3042** [comment]
@martijnwalraven Thanks for your quick response, I agree disclosing header information is not an idea approach. However, my use case requires to fetch the authorization headers from server asynchronously for every request, which required to hold on sending the request until the authorization header fields is fetched. With that said, I doubt the delegate protocol approach will work for this special case and currently I put the authorization header reaching logic inside the application layer, and it will fetch/mutate only when the header fields are successfully fetched. 

Please let me know if you have a better approach to handle setting the header fields  asynchronously, thanks.

**Comment by martijnwalraven** [comment]
Hmmm, do you mean you need fresh credentials for every request? Out of curiosity, what is the server setup that requires that? It seems really inefficient, because you're doing an extra roundtrip per request!

That being said, I think we could still make that work with the delegate approach if we made the method asynchronous.

**Comment by weapon3042** [comment]
@martijnwalraven I agree, actually I have tried to make the delegate method asynchronous, but the side effect is the some functionalites can be broken without a bigger change to HTTPNetworkTransport. Part of the issues is that the URLRequest is added to the operation queue and headers will be fetched and added to the request simultaneously, which can not guarantee the headers are added to the request before the request is executed in the operation queue.  Otherwise, if we have to hold off the request until the headers are properly fetched, a bigger changes in the HTTPNetworkTransport need to by applied.

**Comment by martijnwalraven** [comment]
I'm not sure I understand the problem you're describing. The idea is that we would be modifying the `URLRequest` before starting the session task, so it would block until the credentials have been fetched.

That being said, I still question the sanity of doing this per request :)  So I'm curious to hear the reasons for this requirement.

**Comment by weapon3042** [comment]
@martijnwalraven I have to rephrase it's not making a new request to fetch the headers per request, it's simply a sync API to return the correct HHTP heathers for the current user, so it may or may not make a networking call, most likely making a call only for the first time. As we discussed above, I will adjust this Pull Request to use delegate approach and make it asynchronous. 

Does this sound a good approach to you?

**Comment by martijnwalraven** [comment]
@weapon3042: Yes, that sounds like a good approach, but we may want to spend some time on designing the API first and also consider retrying requests when credentials have expired. I think we could look at [Alamofire](https://github.com/Alamofire/Alamofire#adapting-and-retrying-requests) for inspiration.

**Comment by weapon3042** [comment]
@martijnwalraven Sounds good, thanks for your information!

**Comment by weapon3042** [comment]
Closed for now.

**Pull request closed without merging**
