### PR TITLE
Remove unused type

### PR DESCRIPTION
**Pull request by designatednerd**
Addresses #1425 - @knox, a brief look at other things in the networking stack didn't turn up anything we're not still using, but if you see anything else, shout it out. Thanks!

### CODE REVIEW

**Comment by taher-mosbah** [comment]
Hello @designatednerd, in the changelog I see:
BREAKING: Removed the now-unused-in-the-SDK GraphQLHTTPResponseError type. If you were relying on this class, please copy it out of v0.34.1. (#1437)
but doing that I got: `'textEncoding' is inaccessible due to 'internal' protection level` and `'statusCodeDescription' is inaccessible due to 'internal' protection level` 
is it possible to change that please ?

**Comment by designatednerd** [comment]
You will want to copy the [corresponding extension code](https://github.com/apollographql/apollo-ios/blob/246a2761fa48370a892c2055f245ed5f117fc9f1/Sources/Apollo/HTTPURLResponse%2BHelpers.swift) - you probably want to delete `apollo` and just make it a simple extension on `HTTPURLResponse` rather than the more complex `ApolloExtension` stuff that's in there.

**Comment by vincent-paing** [comment]
What should I use instead of `GraphQLHTTPResponseError`?

**Comment by knox** [comment]
@vincent-paing it's been replaced by `ResponseCodeInterceptor.ResponseCodeError`

**Pull request merged**
