### PR TITLE
support async/await in ApolloCodegenLib

### PR DESCRIPTION
**Pull request by jimisaacs**
Related to this question: https://github.com/apollographql/apollo-ios/issues/3226

This seemed like a good solution to start to using async/await everywhere below ApolloCodegen.build

### CODE REVIEW

**Comment by jimisaacs** [comment]
The latest commit pushed this to a rather larger change, but I still like the changes.

- AsyncParsableCommand makes using async/await in a CLI easy
- XCTest already has great async/await support
- Though upgraded Nimble to 12, which needed its own support for async/await

**Comment by jimisaacs** [comment]
Hmm, rather confused that there are codegen tests run on macOS 13.2, when there is clearly a macOS 15 check in IR.Operation with a fatalError. @BobaFetters @AnthonyMDev, could you provide some insight?

**Comment by jimisaacs** [comment]
Yeah, it might be wait to cumbersome until the build official changes 10.15 as the minimum.

**Comment by calvincestari** [comment]
> Hmm, rather confused that there are codegen tests run on macOS 13.2, when there is clearly a macOS 15 check in IR.Operation with a fatalError. @BobaFetters @AnthonyMDev, could you provide some insight?

I think this is because ApolloCodegenLib requires macOS 15 whereas the other modules support much lower versions of macOS and corresponding APIs in iOS.

**Comment by AnthonyMDev** [comment]
@jimisaacs, thanks for starting this PR. I'm working on a refactoring of a lot of the codegen code right now. When it's finished, I expect that we will raise the minimum deployment target to macOS 15. I also hope to add parallelization to the codegen lib at that time. This seems like a good start, but there are some complications around race conditions when building fragment dependencies that need a bit more work than this.

I'm not going to be accepting a PR for async/await additions at the moment, but once I've got this refactoring work done, I'll be looking into this further.

**Pull request closed without merging**
