### PR TITLE
Swift 5 and Xcode 10.2 support

### PR DESCRIPTION
**Pull request by fassko**

### CODE REVIEW

**Comment by martijnwalraven** [comment]
Thanks for the PR! But I'm hoping now that Xcode 10.2 is out we can land the more comprehensive #475.

**Comment by fassko** [comment]
@martijnwalraven Thanks. That PR #475 would be great. In this PR I updated Starscream. I released Swift 5 and Xcode 10.2 support for that library. Although there is still hanging #466

**Comment by martijnwalraven** [comment]
What do you think we should do while we wait for #475? Any chance you can update #466 with the new Starscream version? Or would you prefer to close that one and merge this PR instead?

**Comment by fassko** [comment]
I will update #466 so it could be easier to merge after #475 I hope it will be soon merged. :)

**Comment by martijnwalraven** [comment]
Closing this in favor of #475 and #466.

**Pull request closed without merging**
